// @ts-nocheck
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import NavTop from "../components/NavTop";
import NavUser from "@/components/NavUser";
import FrameDiv from "../components/FrameDiv";
import FormCustom from "../components/FormCustom";
import { Session } from "next-auth";
import { getAllUrls } from "@/utils/dbActions";
import { tableData } from "../utils/types";
import CustomTable from "@/components/CustomTable";

export default function Index({ data }: { data: tableData[] }) {
	const router = useRouter();

	const { data: session, status } = useSession();
	if (status == "unauthenticated") {
		router.push("/auth/signin");
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<NavTop />
				<svg
					className="m-auto mx-auto
					md:w-4/6
					mt-6"
					height="1"
					fill="#D9D9D9"
					xmlns="http://www.w3.org/2000/svg"
				>
					<rect width="100%" height="1" />
				</svg>

				<NavUser name={session?.user?.name as string} />
				<FrameDiv>
					<FormCustom session={session as Session}></FormCustom>
					<div className="font-bold text-4xl p-3">
						Recent Requests
					</div>
					<CustomTable data={data} />
				</FrameDiv>
			</main>
		</>
	);
}

// get server side props and show last 5-10 post
export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	const { data, error } = await getAllUrls(session?.user?.id as string, 10);
	console.log(data);
	if (JSON.stringify(error) !== "{}") {
		return {
			props: {
				data: [],
			}, // will be passed to the page component as props
		};
	}

	return {
		props: {
			data: JSON.parse(JSON.stringify(data)),
		}, // will be passed to the page component as props
	};
}
