// @ts-nocheck
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import NavTop from "../components/NavTop";
import NavUser from "@/components/NavUser";
import FrameDiv from "../components/FrameDiv";
import FormCustom from "../components/FormCustom";
import { Session } from "next-auth";
import { getAllUrls } from "@/utils/dbActions";
import { tableData } from "../utils/types";
import CustomTable from "@/components/CustomTable";

export default function Index({ data }: { data: tableData[] }) {
	const router = useRouter();

	// const [url, setUrl] = useState<string>();
	// const [slug, setSlug] = useState<string>(randomCode());
	const { data: session, status } = useSession();
	if (status == "unauthenticated") {
		router.push("/auth/signin");
	}

	// const formHandler = async (e: any) => {
	// 	e.preventDefault();
	// 	// alert if url is empty or custom code is not 5 characters long
	// 	if (url?.length == 0) {
	// 		toast.warning("URL cannot be empty");
	// 		return;
	// 	} else if (slug?.length != 5) {
	// 		toast.warning("Code must be 5 characters long");
	// 		return;
	// 	}

	// 	// if (session?.user ) {
	// 	// 	// check if id key exists in user
	// 	// 	if (!session?.user?.id) {
	// 	// 		toast.error("User not found");
	// 	// 		return;
	// 	// 	}
	// 	// }

	// 	// create a fetch request to the api
	// 	const res = await fetch("/api/url", {
	// 		method: "POST",
	// 		body: JSON.stringify({
	// 			url: url,
	// 			slug: slug,
	// 			userId: session?.user?.id,
	// 		}),
	// 		headers: { "Content-Type": "application/json" },
	// 	});
	// 	const data = await res.json();
	// 	console.log(data);
	// 	if (data.message) {
	// 		toast.error(data.message);
	// 	} else {
	// 		toast.success("URL shortened successfully");
	// 		// refresh page or reload table data
	// 	}
	// };

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<NavTop />
				<svg
					className="m-auto mx-auto
					md:w-4/6
					mt-6"
					height="1"
					fill="#D9D9D9"
					xmlns="http://www.w3.org/2000/svg"
				>
					<rect width="100%" height="1" />
				</svg>

				<NavUser name={session?.user?.name} />
				<FrameDiv>
					<FormCustom session={session as Session}></FormCustom>
					<div>Recent Requests</div>
					<CustomTable data={data} />
				</FrameDiv>
			</main>
		</>
	);
}

// get server side props and show last 5-10 post
export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	const { data, error } = await getAllUrls(session?.user?.id);
	console.log(data);
	if (JSON.stringify(error) !== "{}") {
		return {
			props: {
				data: [],
			}, // will be passed to the page component as props
		};
	}

	return {
		props: {
			data: JSON.parse(JSON.stringify(data)),
		}, // will be passed to the page component as props
	};
}
